---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
- name: ci
- name: semver.opensuse-stemcell
- name: src

input_mapping: 
- src: src

outputs:
- name: versioned-fissile-stemcell-opensuse

run:
  path: ci/tasks/setup-opensuse-stemcell-versions.sh

params:
  DOCKER_REPOSITORY: replace-me
